
services:
  nginx:
    restart: always
    build:  requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - /home/bouhammo/data/wp:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
  

  wordpress:
    restart: always
    build: requirements/wordpress
    container_name: wordpress
    volumes:
      - /home/bouhammo/data/wp:/var/www/html
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: mariadb
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
    depends_on:
      - mariadb
    networks:
      - inception


  mariadb:
    restart: always
    build: requirements/mariadb
    container_name: mariadb
    volumes:
      - /home/bouhammo/data/maria:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - inception


networks:
  inception:
    driver: bridge


